name: final_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/location.svg
    - assets/notification.svg
    - assets/send.svg
    - assets/holiday.svg
    - assets/rental.svg
    - assets/plane.svg
    - assets/hotel.svg
    - assets/other.svg
    - assets/indonesia.webp
