name: final_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  dio: ^5.7.0
  provider: ^6.1.2
  dartz: ^0.10.1
  carousel_slider: ^5.0.0
  infinite_scroll_pagination: ^4.1.0
  get_it: ^8.0.2
  webview_flutter: ^3.0.4
  webview_windows: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/preview.png
    