name: final_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/location.svg
    - assets/notification.svg
    - assets/send.svg
    - assets/holiday.svg
    - assets/rental.svg
    - assets/rental2.svg
    - assets/plane.svg
    - assets/hotel.svg
    - assets/other.svg
    - assets/love.svg
    - assets/place.svg
    - assets/indonesia.webp
    - assets/Bukit_khayangan.webp
    - assets/Kalianda.webp
    - assets/pb.webp
    - assets/GWK.jpg
    - assets/pu.jpg
    - assets/Bromo.jpg
    - assets/Kawah_Ijen.jpg
    - assets/Kepulauan_Seribu.jpg
    - assets/Tumpak_Sewu.jpg
    - assets/Lhok_me.jpg
    - assets/Raja_ampat.jpg
    - assets/Lembah_baliem.jpg
    - assets/Lorentz.jpg
    - assets/Danau_sentani.jpg
    - assets/Danau_toba.png
